//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOpenVR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestOpenVR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cbuffer data :register(b0)
        ///{
        ///	float4x4 worldViewProj;
        ///};
        ///
        ///struct VS_IN
        ///{
        ///	float4 position : POSITION;
        ///	float4 color : COLOR;
        ///};
        ///
        ///struct PS_IN
        ///{
        ///	float4 position : SV_POSITION;
        ///	float4 color : COLOR;
        ///};
        ///
        ///PS_IN VS(VS_IN input)
        ///{
        ///	PS_IN output = (PS_IN)0;
        ///
        ///	output.position = mul(worldViewProj,input.position);
        ///	output.color=input.color;
        ///
        ///	return output;
        ///}
        ///
        ///float4 PS(PS_IN input) : SV_Target
        ///{
        ///	return input.color;
        ///}.
        /// </summary>
        internal static string ColorShader {
            get {
                return ResourceManager.GetString("ColorShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cbuffer data :register(b0)
        ///{
        ///	float4x4 worldViewProj;
        ///};
        ///
        ///struct VS_IN
        ///{
        ///	float4 position : POSITION;
        ///	float4 color : COLOR;
        ///};
        ///
        ///struct PS_IN
        ///{
        ///	float4 position : SV_POSITION;
        ///	float4 color : COLOR;
        ///};
        ///
        ///PS_IN VS(VS_IN input)
        ///{
        ///	PS_IN output = (PS_IN)0;
        ///
        ///	output.position = mul(worldViewProj,input.position);
        ///	output.color=input.color;
        ///
        ///	return output;
        ///}
        ///
        ///float4 PS(PS_IN input) : SV_Target
        ///{
        ///	return input.color;
        ///}.
        /// </summary>
        internal static string NormalTextureShader {
            get {
                return ResourceManager.GetString("NormalTextureShader", resourceCulture);
            }
        }
    }
}
